const fs = require('fs');
const path = require('path');

const articlesPath = path.join(__dirname, '../lib/articles.json');
const articles = JSON.parse(fs.readFileSync(articlesPath, 'utf8'));

const newColumn = {
  id: "foucault-infancia-filosofia-olvido",
  title: "Foucault y la infancia que la filosofía olvidó",
  excerpt: "A 42 años de la muerte de Michel Foucault, su obra sigue siendo uno de los arsenales intelectuales más poderosos para comprender cómo opera el poder. Sin embargo, dejó inconcluso un aspecto decisivo de la biopolítica: nunca teorizó la infancia como población específica.",
  author: "Juan Carlos Rauld Farias",
  date: "23 Jul 2026",
  category: "Filosofía",
  image: "/images/foucault_infancia_biopolitica.jpg",
  content: [
    "A 42 años de la muerte de Michel Foucault (1926-1984)",
    "El 25 de junio de 1984 murió Michel Foucault en el hospital de la Salpêtrière de París, el mismo recinto cuya historia clínica había investigado en sus libros. Tenía 57 años. Cuarenta y dos años después, su obra sigue siendo uno de los arsenales intelectuales más poderosos para comprender cómo opera el poder en las sociedades contemporáneas. Ningún otro filósofo del siglo XX logró hacer de la prisión, la locura, la sexualidad y la clínica objetos de reflexión filosófica con semejante alcance político. La filosofía, después de Foucault, dejó de ser una actividad contemplativa para convertirse en lo que él mismo llamó un diagnóstico del presente: es decir, una herramienta para descifrar las relaciones de poder que nos constituyen como sujetos.",
    "Entre sus principales legados conceptuales se encuentra la noción de biopolítica, con la que describió el modo en que los Estados modernos administran la vida de las poblaciones: la natalidad, la mortalidad, la salud, la higiene, la longevidad, etcétera. Foucault mostró que a partir del siglo XVIII el viejo derecho del soberano de «hacer morir o dejar vivir» fue reemplazado por un poder que se propone «hacer vivir o rechazar hacia la muerte». La fórmula parece abstracta, pero sus consecuencias son brutalmente concretas: quiénes reciben atención médica y quiénes no, qué poblaciones son protegidas y cuáles abandonadas, qué vidas merecen ser vividas y cuáles son desechables o simplemente descartables.",
    "Sin embargo, Foucault dejó inconcluso un aspecto decisivo de la biopolítica: nunca teorizó la infancia como población específica. En toda su obra, los niños aparecen de manera instrumental —como ejemplo del poder disciplinario en la escuela, como ejemplo del dispositivo de sexualidad en la familia burguesa— pero nunca como objeto autónomo de una investigación biopolítica. Esta ausencia no es accidental. Foucault trató a «la población» como un bloque homogéneo, sin desagregar sus componentes etarios, y esa limitación analítica ha impedido advertir que las tecnologías de gobierno operan de manera radicalmente diferente sobre un adulto que sobre un niño. La infancia desde esta perspectiva, es un tipo de población que no puede gobernarse a sí misma y que depende enteramente del Estado para mantener a salvo su vida. En ese sentido, constituye un objeto privilegiado del biopoder.",
    "Pese a la omisión recién indicada, la biopolítica foucaultiana es un paradigma extraordinariamente productivo para estudiar las condiciones de vida y muerte de la infancia. Lo es porque permite ver algo que otras perspectivas no alcanzan a iluminar: que la protección y la desprotección infantil no son accidentes ni fallas del sistema, sino efectos de racionalidades de gobierno. Cuando un Estado decide cuánto invierte en salud infantil, cuántos niños institucionaliza, qué familias interviene y cuáles abandona, está ejerciendo biopolítica. Y cuando ese ejercicio produce muerte, desprotección o daño sistemático, estamos ante lo que Foucault denominó el «rechazar hacia la muerte»: es decir, no matar directamente, sino dejar morir. Esta racionalidad, se aplica también a la vejez y a toda población cuya vida es administrada por racionalidades de gobierno que calculan el costo político de proteger o desproteger.",
    "En sus últimos cursos en el Collège de France, Foucault introdujo una distinción que ilumina esta problemática. Llamó Biopoética a la capacidad del individuo de transformar su existencia en una obra de arte, de ejercer sobre sí mismo una estética de la vida. La pregunta inmediata que surge aquí es ineludible: ¿puede un niño pobre ejercer la biopoética? ¿Tiene la infancia pobre o del bajo pueblo la posibilidad de transformarse a sí misma como sujeto moral o político? La respuesta es negativa. La infancia —y particularmente la infancia pobre— es la dimensión humana y poblacional en la que el poder opera de forma hegemónica, sin el contrapeso de una resistencia biopoética, estética o artística. A diferencia de lo que sostuvo Foucault en la Historia de la sexualidad, la sexualidad no es la dimensión más brutal del poder, pero sí la más polémica. La verdadera brutalidad reside en el sometimiento de una población que, desde su nacimiento, está inexorablemente subordinada a las lógicas del poder sin capacidad alguna de contestación.",
    "Basta mirar las cifras actuales para confirmar lo que la filosofía anuncia. El sesgo etario y de la pobreza es estructural: ser niño en Chile duplica la probabilidad de ser pobre. Toda la evidencia científica no es neutra: es el resultado de racionalidades gubernamentales que distribuyen la vida y la muerte de manera desigual. Pero la biopolítica no es solo una máquina de desprotección. También existen experiencias que muestran cómo las racionalidades de gobierno pueden orientarse a reafirmar la vida infantil. Un ejemplo al respecto, es el caso de Uruguay con su programa \"Uruguay Crece Contigo\", -inspirado en nuestro país, -\"Chile Crece Contigo\"-, ha desarrollado un sistema de protección integral a la primera infancia con cobertura nacional y enfoque de derechos. No nos interesa evaluar aquí, cuál sistema es mejor que el otro. No obstante, la diferencia entre el modelo uruguayo, de corte corporativista y universal, y el chileno, de orientación neoliberal y focalizada, muestra que las decisiones de gobierno sobre la infancia no son naturales ni inevitables: son decisiones políticas. Lo que Foucault enseñó, y lo que su obra inconclusa nos exige pensar, es que toda política de infancia es una biopolítica: Un ejemplo de ella, es la infancia institucionalizada en el sistema de desprotección de cuidado residencial. Vale decir, una forma de administrar la vida de quienes no pueden administrarla por sí mismos. La pregunta ética y política es si esa administración se orienta concretamente hacia el hacer vivir o a dejar morir.",
    "La herencia de la filosofía política de Foucault, nos ha permitido mostrar que la institucionalización infantil a cargo del Estado, opera como una estrategia de control y gobierno de la población, en la que se ejerce un poder gubernamental que puede hacerlos morir. Lo que llamo infancia pobre o infancia del bajo pueblo no es una categoría sociológica descriptiva, sino una categoría biopolítica que se utiliza para designar a quienes son gobernados sin protección, administrados sin cuidado y sometidos sin resistencia posible a la experimentación tecnocrática y de mala calidad estatal.",
    "A cuarenta y dos años de su muerte, Foucault sigue siendo un artificiero: Sus conceptos permiten politizar y analizar, el cálculo gubernamental allí donde el poder se ejerce como natural. La infancia olvidada por la filosofía y la herencia de la biopolítica, aguardan todavía su genealogía. Solo con una férrea indocilidad reflexiva, lograremos una escritura comprometida con las formas de dominación que atentan contra la niñez pobre, y al mismo tiempo, seremos críticos con la filosofía y con el propio Foucault. En esto consiste, -me parece a mí-, el mayor elogio el pensador de Poitiers.",
    "Juan Carlos Rauld Farias. Doctorando Internacional en trabajo social de la Universidad Rovira I Virgilli. Magíster en pensamiento contemporáneo en filosofía política. Trabajador social de la Universidad Tecnológica Metropolitana."
  ]
};

// Insert at the beginning so it becomes the newest/featured article
articles.columns.unshift(newColumn);
fs.writeFileSync(articlesPath, JSON.stringify(articles, null, 2));
console.log('Successfully added Foucault column as the newest article.');
